function createfigure(XMatrix1, YMatrix1, ZMatrix1, X1, Z1, X2, Y1, Z2, xdata1, ydata1, zdata1, X3)
%CREATEFIGURE(XMatrix1, YMatrix1, ZMatrix1, X1, Z1, X2, Y1, Z2, xdata1, ydata1, zdata1, X3)
%  XMATRIX1:  matrix of x data
%  YMATRIX1:  matrix of y data
%  ZMATRIX1:  matrix of z data
%  X1:  vector of x data
%  Z1:  vector of z data
%  X2:  vector of x data
%  Y1:  vector of y data
%  Z2:  vector of z data
%  XDATA1:  surface xdata
%  YDATA1:  surface ydata
%  ZDATA1:  surface zdata
%  X3:  vector of x data

%  Auto-generated by MATLAB on 31-May-2023 20:20:43

% Create figure
figure1 = figure('WindowState','maximized');

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot3
plot31 = plot3(XMatrix1,YMatrix1,ZMatrix1,'Parent',axes1,'LineWidth',2);
set(plot31(1),'Color',[0 0 0]);
set(plot31(2),'Color',[0 1 0]);
set(plot31(3),'Color',[0 0 1]);

% Create plot3
plot3(X1,X1,Z1,'Color',[1 0 0]);

% Create multiple lines using matrix input to plot3
plot32 = plot3(X2,Y1,Z2,'LineWidth',2,'LineStyle','none','Color',[0 0 1]);
set(plot32(1),'Marker','o');
set(plot32(2),'Marker','*');

% Create multiple lines using matrix input to plot3
plot33 = plot3(X2,Y1,Z2,'LineWidth',2,'LineStyle','none','Color',[0 0 0]);
set(plot33(1),'Marker','o');
set(plot33(2),'Marker','*');

% Create multiple lines using matrix input to plot3
plot34 = plot3(X2,Y1,Z2,'LineWidth',2,'LineStyle','none','Color',[0 1 0]);
set(plot34(1),'Marker','o');
set(plot34(2),'Marker','*');

% Create surf
surf(xdata1,ydata1,zdata1,'Parent',axes1,'FaceAlpha',0.1,...
    'FaceColor',[1 0 1],...
    'EdgeColor','none');

% Create plot3
plot3(X3,X3,X3,'Marker','*','LineWidth',2,'LineStyle','none',...
    'Color',[1 0 0]);

% Create zlabel
zlabel('$z$','FontWeight','bold','FontSize',14,'Interpreter','latex');

% Create ylabel
ylabel('$y$','FontWeight','bold','FontSize',14,'Interpreter','latex');

% Create xlabel
xlabel('$x$','FontWeight','bold','FontSize',14,'Interpreter','latex');

view(axes1,[27.6650078659224 26.6765217080753]);
grid(axes1,'on');
axis(axes1,'tight');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'DataAspectRatio',[1 1 1]);
