function Hd = filt
%FILT Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.10 and DSP System Toolbox 9.12.
% Generated on: 22-Nov-2023 17:24:00

% Equiripple Differentiator filter designed using the FIRPM function.

% All frequency values are normalized to 1.

N = 10;              % Order
F = [0 0.5 0.55 1];  % Frequency Vector
A = [0 1 0 0];       % Amplitude Vector
W = [1 1];           % Weight Vector

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, F, A, W, 'differentiator');
% Hd = dfilt.dffir(b);

% [EOF]
